### ISSUE TITLE
Having images in the repository will blow up the size of the repo (and it's history)

### ISSUE THREAD

**Issue by ijnek** [ros-sports/soccer_interfaces#19]
Must upload images elsewhere, or setup a docs repository to store the images.

**Comment by Flova** [comment]
Afaik if you paste an image in the GitHub Markdown editor it gets stored on a GitHub CDN and linked.

**Comment by ijnek** [comment]
When using the markdown editor, that would work, but not being able to edit the README locally isn't ideal.

If storing all images in the git repo, my concern isn't much that the files itself take up space, but that the initial clone can take a huge amount of time, as every version of every file has to be downloaded by the client.

Old images that have been modified / removed have to be stored in the git repo. Using `git clone --depth 1` is a work-around but is definitely not a solution.

I'm thinking of using Git LFS such that all the copies of the images don't have to be stored.
Perhaps, I might rewrite history to reduce the current repo size.

Does this sound reasonable @Flova ?

**Comment by ijnek** [comment]
Git LFS seems to have it's own limitations, like a monthly bandwidth quota of 1 GB, decided that moving to rtd is better in long term.
