### ISSUE TITLE
Avoid using 3d coordinates when dealing with image data

### ISSUE THREAD

**Issue by ijnek** [ros-sports/soccer_interfaces#21]
With [this suggestion](https://github.com/ros-perception/vision_msgs/issues/65) getting merged, I'm thinking we shouldn't use [geometry_msgs/Point in Ball.msg](https://github.com/ros-sports/soccer_interfaces/blob/64ce1a2149c7b3df4d9f7f337a0a2b4baf08fce3/soccer_vision_msgs/msg/Ball.msg#L10). 

Maybe we could raise a vision_msgs/Point PR in vision_msgs?

**Comment by ijnek** [comment]
PR in vision_msgs raised: https://github.com/ros-perception/vision_msgs/pull/67

**Comment by ijnek** [comment]
With the PR above merged, we should modify our messages to use Point2D.

**Comment by Flova** [comment]
Using the vision_msgs point sounds reasonable.
