### ISSUE TITLE
Add RViz2 Visualizations for the 3D Messages.

### ISSUE THREAD

**Issue by Flova** [ros-sports/soccer_interfaces#39]
Pull request #38 adds visualizations for a subset of properties. If more features, like the field markings or left/right goal differentiation are used, visualizations should also be added for them.

**Comment by ijnek** [comment]
Field markings have been added. Although left/right goal differentiation has not been added, feel free to create an issue over at https://github.com/ros-sports/soccer_vision_3d_rviz_markers if you think it should be tracked.
